CREATE TABLE tbl_account (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	USERNAME VARCHAR2(100) NOT NULL,
	PASSWORD VARCHAR2(128) NOT NULL,
	SIGNUP_DATE VARCHAR2(50),
	LAST_SIGNIN VARCHAR2(50)

);

CREATE TABLE tbl_recipe (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	RECIPE_OWNER INTEGER,
	RECIPE_NAME VARCHAR2(50) NOT NULL,
	FOREIGN KEY(RECIPE_OWNER) REFERENCES tbl_account(ID)
);

CREATE TABLE tbl_logs (
	ID INTEGER PRIMARY AUTOINCREMENT,
	USERID INTEGER,
	PLATFORM VARCHAR2(50),
	USER_AGENT VARCHAR2(255),
	REQ_TIME VARCHAR2(50)
);

/* Get Recipe based on user */
SELECT * FROM TBL_RECIPE R 
JOIN TBL_ACCOUNT A ON A.ID = R.RECIPE_OWNER 
WHERE RECIPE_OWNER = 12

/* Get Recipes for search results*/
SELECT * FROM TBL_RECIPE
WHERE RECIPE_NAME like '%search string%'

/* Update last user sign in value */
UPDATE tbl_account
SET LAST_SIGNIN = ('New Sign In Date')
WHERE USERNAME = ('Given Username')